version: '3'

services:
  app:
    build: .
    container_name: micro-codeflix
    entrypoint: ./.docker/entrypoint.sh
    user: node
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - 3002:3000
    tty: true